### 실습 sort 알고리즘 만들어보기

1.input -> [2,4,5,1,3]

2.output ->[1,2,3,4,5]

3.sort algorithm

4.for,if 문으로 해결 (sort관련 함수 사용불가)

In [52]:
x=[2,4,5,1,3]

In [56]:
range(1,5)

range(1, 5)

In [18]:
z=[]
for y in range(len(x)-1):
        print("x= " ,y)
        min_idx = y
        for j in range(y+1,len(x)):
            print("y = {}, j={}".format(x[y],x[j]))
            if x[j]<x[min_idx]:
                min_idx = j
        x[y],x[min_idx] = x[min_idx],x[y]
        print("x= ",x)
        print("-"*20)
        

x=  0
y = 2, j=4
y = 2, j=5
y = 2, j=1
y = 2, j=3
x=  [1, 4, 5, 2, 3]
--------------------
x=  1
y = 4, j=5
y = 4, j=2
y = 4, j=3
x=  [1, 2, 5, 4, 3]
--------------------
x=  2
y = 5, j=4
y = 5, j=3
x=  [1, 2, 3, 4, 5]
--------------------
x=  3
y = 4, j=5
x=  [1, 2, 3, 4, 5]
--------------------


In [19]:
a=[2,4,5,1,3]

for i in range(0, len(a)-1):
    min_idx=i
    for j in range(i+1, len(a)):
        if a[j]<a[min_idx]:
            min_idx = j
    a[i],a[min_idx]=a[min_idx], a[i]

In [25]:
def sel_sort(s):
    for i in range(0, len(a)-1):
        min_idx=i
        for j in range(i+1, len(a)):
            if a[j]<a[min_idx]:
                min_idx = j
        a[i],a[min_idx]=a[min_idx], a[i]
    print("sort result = ",a)
    return a

In [27]:
a=[9,4,6,4,7,1,8,2]
sel_sort(a)

sort result =  [1, 2, 4, 4, 6, 7, 8, 9]


[1, 2, 4, 4, 6, 7, 8, 9]

In [30]:
b=sel_sort(a)
print("sort 후= ",b)


sort result =  [1, 2, 4, 4, 6, 7, 8, 9]
sort 후=  [1, 2, 4, 4, 6, 7, 8, 9]


## (실습 입력값을 임의의 숫자로 구성)

1.np.random.choice

In [35]:
import numpy as np
np.random.choice(5,4)

array([4, 3, 0, 1])

In [37]:
np.random.choice(10,5, replace=False)# 비복원 추출

array([1, 5, 9, 6, 8])

In [38]:
x=np.random.choice(10,5, replace=False)
sel_sort(x)

sort result =  [1, 2, 4, 4, 6, 7, 8, 9]


[1, 2, 4, 4, 6, 7, 8, 9]

In [41]:
np.random.choice(4,3,replace=False,p=[0.2,0.2,0.3,0.3])

array([1, 3, 2])

In [44]:
np.random.shuffle(a);a

[7, 6, 4, 8, 1, 2, 4, 9]

In [46]:
np.random.seed(10)
np.random.randint(10, size=5)

array([9, 4, 0, 1, 9])

In [47]:
def bubble_sort(a):
    n=len(a)
    while True:
        changed = False
        
        for i in range(0,n-1):
            if a[i] > a[i+1]:
                print(a)
                a[i],a[i+1]=a[i+1],a[i]
                changed =true
            
        if changed == False:
            return   
        

In [48]:
x=np.random.choice(10,5, replace=False)
sel_sort(x)

sort result =  [1, 2, 4, 4, 6, 7, 8, 9]


[1, 2, 4, 4, 6, 7, 8, 9]