In [2]:
import numpy as np

In [14]:
redwine=np.loadtxt(fname="https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",delimiter=";",skiprows=1)

In [15]:
redwine

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [16]:
redwine.sum()

152084.78194

In [17]:
redwine.mean()

7.926036165311652

In [19]:
redwine.mean(axis=1)#0번 축에대한 평균

array([ 6.21198333, 10.25456667,  8.30825   , ...,  8.37347833,
        8.76795583,  7.7077075 ])

In [26]:
arr = np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr.sum()

21

In [28]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

In [29]:
arr.mean(axis=1)

array([2., 5.])

In [30]:
arr = np.arange(1,13).reshape(2,3,2)
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [32]:
arr.mean(axis=0)

array([[4., 5.],
       [6., 7.],
       [8., 9.]])

In [33]:
arr.mean(axis=1)

array([[ 3.,  4.],
       [ 9., 10.]])

In [34]:
arr.mean(axis=2)

array([[ 1.5,  3.5,  5.5],
       [ 7.5,  9.5, 11.5]])

In [37]:
redwine[:,0].mean()

8.31963727329581

In [38]:
redwine.mean(axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

In [39]:
redwine.max(axis=1)

array([34., 67., 54., ..., 40., 44., 42.])